### ISSUE TITLE
Removing non-core dependencies

### ISSUE THREAD

**Issue by tseemann** [jvolkening/p5-BioX-Seq#2]
This is the package I have been looking for - so much so I was going to write my own!

Is it pure Perl 5 ?

ie. can i bundle it with my code to avoid requiring users to install the modules.

**Comment by jvolkening** [comment]
It is pure P5 in the sense that there is no compiled code involved, so it can be easily bundled, yes.

As far as dependencies, the `BioX::Seq` class itself has zero dependencies. For the `BioX::Seq::Stream` parser, the only non-core dependency is `File::Which`, which it uses to look for `gzip` and other utilities on the system to use for fast transparent decompression. It these utilities are missing, it does fall back to (slow) core perl modules for decompression. It should be pretty easy to remove the `File::Which` dependency with a few extra lines code, so if this is an issue for you feel free to submit a separate issue request for this -- or, even better, a PR.

For `BioX::Seq::Fetch`, the only non-core dependency is for `Compress::BGZF`, but this is only `require`d if you try to read a BGZF-compressed file. `Compress::BGZF` has zero non-core dependencies, so it could be bundled as well.

Hope this helps.

**Comment by tseemann** [comment]
I recommend using this *core* Perl module instead:

https://perldoc.perl.org/IO/Uncompress/AnyUncompress.html

This will save effort uncompressing _and_ remove your `File::Which` dependency.

```
use IO::Uncompress::AnyUncompress;
my $unzip = IO::Uncompress::AnyUncompress->new($fname);
while (<$unzip>) {
}
```

**Comment by jvolkening** [comment]
Thanks -- that is an interesting core module that I was unaware of.

Currently the streaming parser falls back on `IO::Uncompress::Gunzip` and `IO::Uncompress::Bunzip2` (which are also core modules) if a relevant system binary is not found by `File::Which`. The reason for this is performance -- the perl modules were **much** slower than the system calls in benchmarking, even using the unthreaded versions. Do you have any experience with the module you mention re: speed?

A second complication is that the streaming parser checks for several compression formats unsupported by the module you mention: zstd as well as two sequence-specific formats (DSRC, FQZ). Thus, it still wouldn't be quite as simple as the code you have above.

I'm going to re-open and re-title this to keep it on the radar. At some point I may look into removing the File::Which dependency (PRs are welcome too).

**Comment by tseemann** [comment]
moved from `gzip -dcf file.gz |` to the core modules and didn't notice anythjing, bitI didn't test speed - i only use it on contig FASTA files and reading them was not the bottleneck. But I believe you when you say they aren't fast; it's a common zlib complaint!

**Comment by tseemann** [comment]
```
#!/usr/bin/env perl
use strict;
use File::Spec;  # core module

for my $exe (qw(ls sort awk gzip fakecmd perl)) {
  my $path = which($exe) || 'NOT FOUND';
  print "$exe => $path\n";
}

sub which {
  my($exe) = @_;
  for my $dir (File::Spec->path) {
    my $path = File::Spec->catfile($dir,$exe);
    return $path if -x $path;
  }
  return;
}
```

**Comment by jvolkening** [comment]
>  I only use it on contig FASTA files and reading them was not the bottleneck

I can see that, but it definitely makes a difference parsing FASTQ data.

>     return $path if -x $path;
Probably would need to be
```
return $path if (-x $path && ! -d $path);
```

This is basically what `File::Which` is doing, but it also checks some additional edge cases (such as that binaries on Windows can have *.exe extensions). I guess the question is whether those edge cases are important. I don't use Windows myself, but I've taken the time in the past to test for full compatibility and I'm not sure I want to abandon that.

Out of curiosity, what is the use case of needing to avoid all non-core dependencies? After all, `BioX::Seq` would be a non-core dependency itself.

**Comment by jvolkening** [comment]
OP has gone in a different direction, and we have no internal need to remove these dependencies. Closing until future need arises.

**Comment by tseemann** [comment]
Why? I would want to bundle BioX::Seq in my code directly, and not depend on CPAN.

**Comment by jvolkening** [comment]
@tseemann,

It's been a while since you opened the issue, but I recently learned of the core module `IPC::Cmd` which has a function to do the same thing as `File::Which`. I believe all modules used should now be core as of Perl 5.12 or so. The exception is `Compress::BGZF`, but this is `require`ed and not `use`ed only conditionally, so the module can be installed/used without it.
